/* Copyright Avaya Inc. */

#import <Foundation/Foundation.h>

#import "CSCredentialProvider.h"

/**
 * Configuration information for Push Notifications.
 */
@interface CSPushNotificationConfiguration : NSObject

/**
 * A Boolean value indicating whether Push Notifications are enabled.
 */
@property (nonatomic, getter=isEnabled) BOOL enabled;

/**
 * The address information for the telephony event push notification service
 *
 * Example: https://server_address:server_port/
 */
@property (nonatomic, copy) NSURL *telephonyPushNotificationServiceURL;

/**
 * A globally unique app-specific device token generated by the 
 * Apple Push Notification Service and assigned to this application
 * instance when the iOS application registers with the service to receive
 * notifications.
 */
@property (nonatomic, strong) NSString *pushToken;

/**
 * Application identifier in the form com.domain.application
 */
@property (nonatomic, strong) NSString *applicationBundleId;

/**
 * The credential provider
 */
@property (nonatomic, weak) id <CSCredentialProvider> credentialProvider;

/**
 * A Boolean value indicating whether incoming push notification events should
 * be sent through Apple's development push notification network
 * (api.development.push.apple.com) or the production push notification network
 * (api.push.apple.com). The Boolean flag is set to YES  if the application is built
 *  using a development provisioning profile. By default, the property is
 * set to NO, and Apple's production network is used to route push notification
 * messages.
 */
@property (nonatomic) BOOL useDevelopmentPushNotificationNetwork;

@end
